# Generated by Django 4.2.4 on 2023-08-24 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('us_list', '0003_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
