# Generated by Django 4.2.4 on 2023-08-26 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('us_list', '0005_alter_excelfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='account_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
